//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class klients
    {
        public int klientsID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> carsID { get; set; }
    
        public virtual cars cars { get; set; }
    }
}
